/**
 * [lie.js]
 * Let working addEventListener, document.getElementsByClassName.. etc in Internet Explorer
 *
 * @author prevdev@gmail.com
 *
 * source code in https://github.com/Prev/liejs
 * built in 2013.2.15
 *
 * MIT LICENSE
 */
 (function(d,w){function NodeList(a){if(a){for(var i=0;i<a;i++)this[i]=0;this.length=parseInt(a)}else this.length=0}NodeList.prototype={item:function(a){return this[a]},__push:function(a){var b=this.length;this[b]=a;this.length++},toString:function(){return"[object NodeList]"}};if(!d.getElementById){if(d.querySelector){d.getElementById=function(a){return d.querySelector("#"+a)}}else if(d.getElementsByTagName){d.getElementById=function(a){var t=d.getElementsByTagName("*");for(var i=0;i<t.length;i++){if(t[i].id==a)return t[i]}}}else if(d.all){d.getElementById=function(a){return d.all[a]}}else if(d.layers){d.getElementById=function(a){return d.layers[a]}}}if(!d.getElementsByClassName){if(d.querySelectorAll){d.getElementsByClassName=function(a){return d.querySelectorAll("."+a)}}else if(d.getElementsByTagName){d.getElementsByClassName=function(a){var t=d.getElementsByTagName("*");var n=new NodeList();for(var i=0;i<t.length;i++){var b=t[i].className.split(" ");if(b.indexOf(a)!=-1)n.__push(t[i])}return n}}}if(!d.querySelector){if(d.getElementById&&d.getElementsByClassName&&d.getElementsByTagName){d.querySelector=function(a){var s=a.substr(1,a.length-2);switch(a.substr(0,1)){case"#":return d.getElementById(s);break;case".":return d.getElementsByClassName(s).item(0);break;default:return d.getElementsByTagName(a).item(0);break}}}}if(!d.querySelectorAll){if(d.getElementById&&d.getElementsByClassName&&d.getElementsByTagName){d.querySelectorAll=function(a){var s=a.substr(1,a.length-2);switch(a.substr(0,1)){case"#":var n=new NodeList();n.__push(d.getElementById(s));return n;break;case".":return d.getElementsByClassName(s);break;default:return d.getElementsByTagName(a);break}}}}function addListenerFuncs(t){if(!t.addEventListener){if(t.attachEvent)t.addEventListener=function(a,b,c){this.attachEvent("on"+a,b)};else t.addEventListener=function(a,b,c){this["on"+a]=b}}if(!t.removeEventListener){if(t.detachEvent)t.removeEventListener=function(a,b){this.detachEvent("on"+a,b)};else t.removeEventListener=function(a,b){if(b==this["on"+a])this["on"+a]=null}}}addListenerFuncs(d);if(!w.addEventListener){addListenerFuncs(w);d.addEventListener("readystatechange",function(){if(d.readyState=="complete"||d.readyState=="loaded"){for(var k in d.all){var m=d.all[k];addListenerFuncs(m)}for(var i=0;i<d.forms.length;i++){var m=d.forms[i];addListenerFuncs(m)}}},true)}if(!Array.prototype.indexOf){Array.prototype.indexOf=function(a,b){if(!b)b=0;for(var i=b;i<this.length;i++){if(this[i]===a)return i}return-1}}if(typeof String.prototype.trim!=='function'){String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,'')}}})(document,window);